# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73ca2ae36b25907d192487e41b6f2f5565715037b4a8225dc5228d2b74c4e68184e414ba037ef2f468bf677ae45bcb6aa37566ef23b145cdb6b5ad77b62c4dbd

test:
  secret_key_base: 66e4957938f86225f9f71ca554f5a55fc4851b3e27501f9700d2aa5e7942983df95fd6c6d48fdcb5ece045325306c77294b00fd57e544ff17b0a974f4f10299d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
